<?php

return [
    // Fixed list of Pontianak city government work units (satuan kerja).
    // Single source of truth for both registration validation and the
    // dropdown options sent to the frontend — add/remove units here only.
    'list' => [
        'BADAN KEPEGAWAIAN DAN PENGEMBANGAN SUMBER DAYA MANUSIA',
        'BADAN KESATUAN BANGSA DAN POLITIK',
        'BADAN KEUANGAN DAN ASET DAERAH',
        'BADAN PENANGGULANGAN BENCANA DAERAH',
        'BADAN PENDAPATAN DAERAH',
        'BADAN PERENCANAAN PEMBANGUNAN, RISET DAN INOVASI DAERAH',
        'DINAS KEPEMUDAAN, OLAHRAGA DAN PARIWISATA',
        'DINAS KEPENDUDUKAN DAN PENCATATAN SIPIL',
        'DINAS KESEHATAN',
        'DINAS KOMUNIKASI DAN INFORMATIKA',
        'DINAS KOPERASI, USAHA MIKRO DAN PERDAGANGAN',
        'DINAS LINGKUNGAN HIDUP',
        'DINAS PANGAN, PERTANIAN DAN PERIKANAN',
        'DINAS PEKERJAAN UMUM DAN PENATAAN RUANG',
        'DINAS PENANAMAN MODAL DAN PELAYANAN TERPADU SATU PINTU',
        'DINAS PENDIDIKAN DAN KEBUDAYAAN',
        'DINAS PENGENDALIAN PENDUDUK, KB, PEMBERDAYAAN PEREMPUAN DAN PERLINDUNGAN ANAK',
        'DINAS PERHUBUNGAN',
        'DINAS PERPUSTAKAAN DAN KEARSIPAN',
        'DINAS PERUMAHAN RAKYAT DAN KAWASAN PERMUKIMAN',
        'DINAS SOSIAL',
        'DINAS TENAGA KERJA',
        'INSPEKTORAT',
        'KECAMATAN PONTIANAK BARAT',
        'KECAMATAN PONTIANAK KOTA',
        'KECAMATAN PONTIANAK SELATAN',
        'KECAMATAN PONTIANAK TENGGARA',
        'KECAMATAN PONTIANAK TIMUR',
        'KECAMATAN PONTIANAK UTARA',
        'SATUAN POLISI PAMONG PRAJA',
        'SEKRETARIAT DAERAH',
        'SEKRETARIAT DPRD',
    ],
];
